apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: e2e-builder
  name: e2e-builder
spec:
  containers:
  - args:
    - sleep
    - "100000"
    image: golang:1.14
    name: e2e-builder
    resources: {}
    volumeMounts:
    - name: k8s
      mountPath: /go/src/k8s.io      
  volumes:
  - name: k8s
    hostPath:
       path: ${K8S_ROOT}       
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
